image: golang:1.12.9-stretch

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/eddiewebb/studio-light

before_script:
  - apt-get update
  - apt-get -y install libusb-1.0-0-dev

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go mod download
    - CGO_LDFLAGS_ALLOW='-fconstant-cfstrings' go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/calendar-blync
  artifacts:
    paths:
      - calendar-blync
